# Deployment

## Build time

### Build docker image
```
docker build -t arjunrao87/world-countries-graphql-api .
```

### Tag docker image
```
docker tag arjunrao87/world-countries-graphql-api:latest arjunrao87/world-countries-graphql-api:1.3.0
```

### Push docker image
```
docker push arjunrao87/world-countries-graphql-api:1.3.0
```

## Deploy time

### Bring up services using Docker Compose
```
docker-compose up --scale countries=3
```