countries:
  image: arjunrao87/world-countries-graphql-api:1.5.0
  volumes:
    - .:/app
  ports:
    - "${SERVER_PORT}:5000"
  restart: always

reverseproxy:
  image: nginx
  links:
    - countries
  volumes_from:
    - countries
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/countries.conf:ro
  ports:
    - "8080:8080"
  restart: always
